function testNetworkPixelLayout()
%TESTNETWORKPIXELLAYOUT Lock every physical control to its source pixels.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'levels'));
addpath(fullfile(projectRoot, 'src'));
world = continuousCampusWorld();
network = world.mechanic.network;

scaleX = network.pageRect(3) / network.pagePixelSize(1);
scaleY = network.pageRect(4) / network.pagePixelSize(2);
assert(abs(scaleX - scaleY) < 1e-12, ...
    'The complete campus-network page is not uniformly scaled.');
assert(network.pageRect(1) >= world.regions(3).xRange(1) && ...
    network.pageRect(1) + network.pageRect(3) <= ...
    world.regions(3).xRange(2), ...
    'The complete campus-network page left its continuous region.');

pixels = network.controlPixels;
expected = [ ...
    pixelRectToWorld(network.pageRect, pixels.noticePanel, ...
        network.pagePixelSize); ...
    pixelRectToWorld(network.pageRect, pixels.usernameField, ...
        network.pagePixelSize); ...
    pixelRectToWorld(network.pageRect, pixels.passwordField, ...
        network.pagePixelSize); ...
    pixelRectToWorld(network.pageRect, pixels.rememberCheckbox, ...
        network.pagePixelSize); ...
    pixelRectToWorld(network.pageRect, pixels.loginButton, ...
        network.pagePixelSize); ...
    pixelRectToWorld(network.pageRect, pixels.selfServiceButton, ...
        network.pagePixelSize); ...
    pixelRectToWorld(network.pageRect, pixels.onlineRecharge, ...
        network.pagePixelSize); ...
    pixelRectToWorld(network.pageRect, pixels.fundRecharge, ...
        network.pagePixelSize)];
actual = [network.noticePanel; network.usernameField; network.passwordField; ...
    network.rememberCheckbox; network.loginButton; ...
    network.selfServiceButton; network.rechargePads];
assert(all(abs(actual - expected) < 1e-12, 'all'), ...
    'A campus-network control moved independently of the page transform.');
end
