function testLevelData()
%TESTLEVELDATA Validate the current continuous-world contract and asset.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
cfg = gameConfig(projectRoot);
world = continuousCampusWorld();
expectedRegions = {'origin', 'northLake', 'network', ...
    'traffic', 'lexue', 'lucy'};

assert(world.id == 1 && strcmp(world.mechanic.type, 'continuousCampus'), ...
    'The runtime entry is not the one continuous campus world.');
assert(isequal({world.regions.id}, expectedRegions), ...
    'Continuous regions are missing or out of narrative order.');
for index = 2:numel(world.regions)
    assert(world.regions(index - 1).xRange(2) == ...
        world.regions(index).xRange(1), ...
        'A visible gap exists between adjacent continuous regions.');
end
assert(size(world.spawn, 1) == 2 && size(world.spawn, 2) == 2, ...
    'The world requires two spawn positions.');
assert(size(world.platforms, 2) == 4 && ...
    all(world.platforms(:, 3) > 0) && all(world.platforms(:, 4) > 0), ...
    'Platform rectangles must have positive dimensions.');
assert(numel(world.checkpoints) == 6, ...
    'The current journey requires its six frozen checkpoints.');
assert(all(world.finish(3:4) > 0) && ...
    world.finish(1) + world.finish(3) <= world.worldWidth + eps, ...
    'Lucy River finish must remain inside the world bounds.');

state = createInitialState(world, cfg, []);
state = stepLevel(state, world, cfg, 0);
state.levelState.lexue.homeActive = true;
state.levelState.lexue.courseCardReached = true;
state.players(1).pos = world.finish(1:2) + [0.8, 0.05];
state.players(2).pos = world.finish(1:2) + [1.8, 0.05];
state = stepLevel(state, world, cfg, 0);
assert(state.completed, ...
    'The world did not accept both players at its only finish.');

assert(isfile(cfg.assets.loginImage), ...
    'The privacy-checked login image is missing from assets/game.');
assert(isfile(cfg.assets.alpacaSprite), ...
    'The generated alpaca sprite is missing from assets/game.');
[~, ~, alpacaAlpha] = imread(cfg.assets.alpacaSprite);
assert(~isempty(alpacaAlpha) && min(alpacaAlpha(:)) == 0 && ...
    max(alpacaAlpha(:)) == 255, ...
    'The alpaca sprite does not contain a usable transparent alpha channel.');
imageInfo = imfinfo(cfg.assets.loginImage);
assert(imageInfo.Width == 1293 && imageInfo.Height == 740, ...
    'The runtime login screenshot dimensions changed unexpectedly.');
end
