function testLevelData()
%TESTLEVELDATA Validate the current continuous-world contract and asset.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
cfg = gameConfig(projectRoot);
world = continuousCampusWorld();
expectedRegions = {'origin', 'northLake', 'network', ...
    'traffic', 'lexue', 'lucy'};

assert(world.id == 1 && strcmp(world.mechanic.type, 'continuousCampus'), ...
    'The runtime entry is not the one continuous campus world.');
assert(isequal({world.regions.id}, expectedRegions), ...
    'Continuous regions are missing or out of narrative order.');
for index = 2:numel(world.regions)
    assert(world.regions(index - 1).xRange(2) == ...
        world.regions(index).xRange(1), ...
        'A visible gap exists between adjacent continuous regions.');
end
assert(size(world.spawn, 1) == 2 && size(world.spawn, 2) == 2, ...
    'The world requires two spawn positions.');
assert(size(world.platforms, 2) == 4 && ...
    all(world.platforms(:, 3) > 0) && all(world.platforms(:, 4) > 0), ...
    'Platform rectangles must have positive dimensions.');
assert(numel(world.checkpoints) == 6, ...
    'The current journey requires its six frozen checkpoints.');
assert(all(world.finish(3:4) > 0) && ...
    world.finish(1) + world.finish(3) <= world.worldWidth + eps, ...
    'Lucy River finish must remain inside the world bounds.');
teaRects = vertcat(world.mechanic.tea.rect);
assert(all(abs(teaRects(:, 3) - 1.5) < eps) && ...
    all(abs(teaRects(:, 4) - 1.8125) < eps) && ...
    abs(cfg.tea.visualWidthMultiplier - 1.25) < eps && ...
    abs(cfg.tea.capWidthMultiplier - 1.14) < eps && ...
    abs(cfg.tea.capHeightMultiplier - 1.08) < eps && ...
    abs(cfg.tea.outlineAlpha - 0.34) < eps && ...
    cfg.tea.outlineRadiusPixels == 1, ...
    'Iced-tea pickups lost their enlarged or softly outlined presentation.');

state = createInitialState(world, cfg, []);
state = stepLevel(state, world, cfg, 0);
state.levelState.lexue.homeActive = true;
state.levelState.lexue.courseCardReached = true;
state.players(1).pos = world.finish(1:2) + [0.8, 0.05];
state.players(2).pos = world.finish(1:2) + [1.8, 0.05];
state = stepLevel(state, world, cfg, 0);
assert(state.completed, ...
    'The world did not accept both players at its only finish.');

assert(isfile(cfg.assets.loginImage), ...
    'The privacy-checked login image is missing from assets/game.');
assert(isfile(cfg.assets.alpacaSprite), ...
    'The generated alpaca sprite is missing from assets/game.');
assert(isfile(cfg.assets.teaSourceImage), ...
    'The user-designated tropical iced-tea source is missing from assets/game.');
assert(isfile(cfg.assets.teaSprite), ...
    'The transparent tropical iced-tea sprite is missing from assets/game.');
[~, ~, alpacaAlpha] = imread(cfg.assets.alpacaSprite);
assert(~isempty(alpacaAlpha) && min(alpacaAlpha(:)) == 0 && ...
    max(alpacaAlpha(:)) == 255, ...
    'The alpaca sprite does not contain a usable transparent alpha channel.');
imageInfo = imfinfo(cfg.assets.loginImage);
assert(imageInfo.Width == 1293 && imageInfo.Height == 740, ...
    'The runtime login screenshot dimensions changed unexpectedly.');
teaSourceInfo = imfinfo(cfg.assets.teaSourceImage);
assert(teaSourceInfo.Width == 447 && teaSourceInfo.Height == 447 && ...
    strcmpi(teaSourceInfo.Format, 'jpg'), ...
    'The designated 447-by-447 JPEG iced-tea source changed unexpectedly.');
expectedTeaHash = ...
    'c7b8b4c64d83bb936e8d7583f019576a41c3288bf2483e7c0343240683f9480d';
assert(strcmp(sha256File(cfg.assets.teaSourceImage), expectedTeaHash), ...
    'The designated iced-tea file bytes changed unexpectedly.');
teaSpriteInfo = imfinfo(cfg.assets.teaSprite);
assert(teaSpriteInfo.Width == 131 && teaSpriteInfo.Height == 421 && ...
    strcmpi(teaSpriteInfo.Format, 'png'), ...
    'The transparent iced-tea PNG dimensions or format changed.');
[~, ~, teaAlpha] = imread(cfg.assets.teaSprite);
assert(~isempty(teaAlpha) && min(teaAlpha(:)) == 0 && ...
    max(teaAlpha(:)) == 255, ...
    'The transparent iced-tea PNG lost its usable alpha channel.');
expectedSpriteHash = ...
    '6a1430969a09cf80e3c4cef6dc48379e71b87151383599256f5669c9695432a3';
assert(strcmp(sha256File(cfg.assets.teaSprite), expectedSpriteHash), ...
    'The transparent iced-tea sprite bytes changed unexpectedly.');
end

function value = sha256File(filePath)
fileId = fopen(filePath, 'rb');
assert(fileId ~= -1, 'Unable to open the iced-tea source for hashing.');
cleanupGuard = onCleanup(@() fclose(fileId));
bytes = fread(fileId, inf, '*uint8');
digest = java.security.MessageDigest.getInstance('SHA-256');
digest.update(typecast(bytes, 'int8'));
value = lower(reshape(dec2hex(typecast(digest.digest(), 'uint8'), 2).', ...
    1, []));
clear cleanupGuard;
end
