function testLexuePixelLayout()
%TESTLEXUEPIXELLAYOUT Lock both Lexue pages to their source pixel grids.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'levels'));
addpath(fullfile(projectRoot, 'src'));
world = continuousCampusWorld();
lexue = world.mechanic.lexue;
pages = [lexue.selectionPageRect; lexue.homePageRect];

scaleX = pages(:, 3) ./ lexue.pagePixelSize(1);
scaleY = pages(:, 4) ./ lexue.pagePixelSize(2);
assert(all(abs(scaleX - scaleY) < 1e-12), ...
    'A Lexue page was stretched independently on one axis.');
assert(abs(scaleX(1) - scaleX(2)) < 1e-12, ...
    'The selection and home pages use different pixel scales.');

lexueRegion = world.regions(5).xRange;
assert(all(pages(:, 1) >= lexueRegion(1)) && ...
    all(pages(:, 1) + pages(:, 3) <= lexueRegion(2)), ...
    'A Lexue page left its continuous-world region.');

layout = lexue.layoutPixels;
expectedCountdown = pixelRectToWorld(lexue.selectionPageRect, ...
    layout.countdownTiles, lexue.pagePixelSize);
expectedStart = pixelRectToWorld(lexue.selectionPageRect, ...
    layout.selectionStartButton, lexue.pagePixelSize);
expectedCourse = pixelRectToWorld(lexue.homePageRect, ...
    layout.homeCourseCard, lexue.pagePixelSize);
assert(size(lexue.countdownPlatforms, 1) == 6 && ...
    all(abs(lexue.countdownPlatforms - expectedCountdown) < 1e-12, 'all'), ...
    'The six source countdown tiles were moved or resized.');
assert(all(abs(lexue.startButtonPlatform - expectedStart) < 1e-12), ...
    'The physical start button left its source pixel box.');
assert(all(abs(lexue.courseCardPlatform - expectedCourse) < 1e-12), ...
    'The physical My Courses card left its source pixel box.');

selectionCard = pixelRectToWorld(lexue.selectionPageRect, ...
    layout.selectionUserCard, lexue.pagePixelSize);
assert(expectedStart(1) >= selectionCard(1) && ...
    expectedStart(1) + expectedStart(3) <= ...
    selectionCard(1) + selectionCard(3), ...
    'The start button no longer sits inside the right user card.');

tutorial = pixelRectToWorld(lexue.homePageRect, ...
    layout.homeTutorial, lexue.pagePixelSize);
profile = pixelRectToWorld(lexue.homePageRect, ...
    layout.homeProfileCard, lexue.pagePixelSize);
assert(tutorial(1) + tutorial(3) < profile(1), ...
    'The homepage left tutorial and right profile columns were reflowed.');
end
