function testWindowsValidationSummary()
%TESTWINDOWSVALIDATIONSUMMARY Reject partial evidence and accept full fixtures.

root = tempname;
folder = fullfile(root, 'windows-validation-results');
mkdir(folder);
guard = onCleanup(@() rmdir(root, 's'));
scales = {'100%', '125%', '150%'};
routes = {'upper', 'lower', 'upper'};
keys = {'primary', 'alternate', 'primary'};
for index = 1:3
    writeText(fullfile(folder, sprintf('validation-%d.txt', index)), ...
        sprintf(['MATLABHI WINDOWS VALIDATION\nispc: 1\n', ...
        'Scale label: %s\nThree minimum FPS results: 48.0 / 47.0 / 46.0\n', ...
        'AUTOMATIC PERFORMANCE AND KEYBOARD CHECKS: PASS\n'], scales{index}));
    writeText(fullfile(folder, sprintf('interactive-%d.txt', index)), ...
        interactiveFixture(scales{index}, routes{index}, keys{index}, index));
end
report = summarizeWindowsValidation(root);
assert(~report.allPassed && report.completedSessions == 3 && ...
    report.humanConfirmedSessions == 0, ...
    'Coverage audit accepted sessions without human visual/control review.');
for index = 1:3
    writeText(fullfile(folder, sprintf('human-%d.txt', index)), ...
        sprintf(['MATLABHI HUMAN PLAYTEST REVIEW\nispc: 1\n', ...
        'Scale: %s\nPlanned route: %s\nPlayer 2 keys: %s\n', ...
        'Session label: %d\nTwo-person session: 1\n', ...
        'Visual readability confirmed: 1\nControl response confirmed: 1\n'], ...
        scales{index}, routes{index}, keys{index}, index));
end
report = summarizeWindowsValidation(root);
assert(report.allPassed, 'Complete target-Windows fixtures were not accepted.');
clear guard;
end

function body = interactiveFixture(scale, route, keys, label)
body = sprintf(['MATLABHI INTERACTIVE PERFORMANCE\nispc: 1\n', ...
    'Scale: %s\nPlanned route: %s\nPlayer 2 keys: %s\n', ...
    'Session label: %d\nTwo-person session: 1\nActual route: %s\n', ...
    'Completed: 1 | game seconds: 60.0\n', ...
    'north-lake     49.0 FPS | 8.0 s | 392 frames | enough sample: 1\n', ...
    'network-race   49.0 FPS | 8.0 s | 392 frames | enough sample: 1\n', ...
    'traffic        49.0 FPS | 8.0 s | 392 frames | enough sample: 1\n', ...
    'bicycle        49.0 FPS | 8.0 s | 392 frames | enough sample: 1\n', ...
    'campus         49.0 FPS | 8.0 s | 392 frames | enough sample: 1\n'], ...
    scale, route, keys, label, route);
end

function writeText(path, body)
file = fopen(path, 'w');
assert(file >= 0, 'Could not create validation fixture.');
guard = onCleanup(@() fclose(file));
fprintf(file, '%s', body);
clear guard;
end
