function drawContinuousBackground(ax, world, cfg)
%DRAWCONTINUOUSBACKGROUND Draw one uninterrupted, readable campus strip.

ink = cfg.presentation.colors.ink;
blue = cfg.presentation.colors.uiBlue;
northLake = world.regions(strcmp({world.regions.id}, 'northLake')).xRange;
network = world.regions(strcmp({world.regions.id}, 'network')).xRange;
traffic = world.regions(strcmp({world.regions.id}, 'traffic')).xRange;
lexue = world.regions(strcmp({world.regions.id}, 'lexue')).xRange;
lucy = world.regions(strcmp({world.regions.id}, 'lucy')).xRange;

% MATLAB origin: the graph remains part of the world rather than a title card.
patch(ax, [0, 12, 12, 0], [0, 0, 11.2, 11.2], ...
    [0.94, 0.97, 0.96], 'EdgeColor', 'none');
plot(ax, [1.0, 1.0], [1.0, 9.4], '-', 'Color', [0.24, 0.34, 0.38], ...
    'LineWidth', 1.8);
plot(ax, [0.8, 11.2], [1.0, 1.0], '-', 'Color', [0.24, 0.34, 0.38], ...
    'LineWidth', 1.8);
x = linspace(1.1, 11.0, 70);
y = 5.0 + 1.1 * sin(0.9 * x) + 0.035 * (x - 6) .^ 2;
plot(ax, x, y, '-', 'Color', [0.76, 0.22, 0.20], 'LineWidth', 2.2);
text(ax, 1.5, 10.2, 'MATLAB 坐标轴入口', ...
    'FontName', cfg.render.fontName, 'FontWeight', 'bold', ...
    'Color', ink, 'FontSize', 14);

% North Lake: water, one supported red-bridge silhouette, and tree scale.
patch(ax, [northLake(1), northLake(2), northLake(2), northLake(1)], ...
    [0.2, 0.2, 6.0, 6.0], ...
    cfg.presentation.colors.water, 'EdgeColor', 'none', 'FaceAlpha', 0.46);
for treeX = (northLake(1) + 2.5):4.2:(northLake(2) - 2)
    plot(ax, treeX, 7.0 + 0.2 * mod(round(treeX), 3), 'o', ...
        'MarkerSize', 23, 'MarkerFaceColor', [0.25, 0.54, 0.31], ...
        'MarkerEdgeColor', [0.14, 0.34, 0.20]);
end
plot(ax, [14.0, 20.5, 27.0], [5.0, 5.7, 5.7], '-', ...
    'Color', [0.65, 0.15, 0.11], 'LineWidth', 5.0);
for supportX = [14.6, 20.5, 26.4]
    plot(ax, [supportX, supportX], [3.5, 5.4], '-', ...
        'Color', [0.35, 0.20, 0.15], 'LineWidth', 2.3);
end
text(ax, 15, 9.2, '北湖 · 动物借道', ...
    'FontName', cfg.render.fontName, 'FontWeight', 'bold', ...
    'Color', [0.12, 0.36, 0.42], 'FontSize', 15);
drawAlpacaShortcut(ax, world.mechanic.animals.shortcutPlatforms, cfg);

% The campus-network interface is rebuilt as geometry around its controls.
rectangle(ax, 'Position', [network(1) + 0.4, 0.55, ...
    diff(network) - 0.9, 10.6], ...
    'FaceColor', [0.96, 0.98, 1.0], 'EdgeColor', [0.62, 0.72, 0.84], ...
    'LineWidth', 1.4, 'Curvature', 0.02);
rectangle(ax, 'Position', [network(1) + 0.4, 9.55, ...
    diff(network) - 0.9, 1.6], ...
    'FaceColor', [0.25, 0.57, 0.84], 'EdgeColor', 'none');
text(ax, network(1) + 1.4, 10.35, '北京理工大学 · 校园网用户认证', ...
    'FontName', cfg.render.fontName, 'FontWeight', 'bold', ...
    'Color', 'white', 'FontSize', 14);
text(ax, network(1) + 1.5, 8.75, '通知公告', ...
    'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', ink);
for rowY = [7.9, 7.25, 6.6]
    plot(ax, network(1) + [1.5, 6.0], [rowY, rowY], '-', ...
        'Color', [0.66, 0.72, 0.78], 'LineWidth', 1.2);
end

% North-to-south transition: an east-west walkway crosses a north-south road.
patch(ax, [traffic(1), traffic(2), traffic(2), traffic(1)], ...
    [0.65, 0.65, 4.1, 4.1], ...
    [0.78, 0.75, 0.68], 'EdgeColor', 'none', 'FaceAlpha', 0.82);
crosswalk = world.mechanic.traffic.crosswalk;
rectangle(ax, 'Position', [crosswalk(1) - 0.15, 0.65, ...
    crosswalk(3) + 0.30, 4.20], ...
    'FaceColor', [0.34, 0.38, 0.41], 'EdgeColor', [0.20, 0.23, 0.25], ...
    'LineWidth', 1.2);
for stripeY = 1.08:0.40:2.48
    rectangle(ax, 'Position', [crosswalk(1) + 0.08, stripeY, ...
        crosswalk(3) - 0.16, 0.17], ...
        'FaceColor', [0.94, 0.94, 0.92], 'EdgeColor', 'none');
end
roadCentre = crosswalk(1) + crosswalk(3) / 2;
plot(ax, [roadCentre, roadCentre], [2.85, 4.65], '--', ...
    'Color', [0.95, 0.92, 0.65], 'LineWidth', 1.4);
for supportX = traffic(1) + [12, 24, 33, 44]
    plot(ax, [supportX, supportX], [4.1, 6.0], '-', ...
        'Color', [0.31, 0.35, 0.38], 'LineWidth', 3.0);
end
text(ax, traffic(1) + 4.2, 10.2, ...
    '南北交通：喷泉上桥 / 红绿灯过街', ...
    'FontName', cfg.render.fontName, 'FontWeight', 'bold', ...
    'Color', ink, 'FontSize', 14);

% Sanitized Lexue page: no personal profile, dates, course history, or links.
rectangle(ax, 'Position', [lexue(1) + 0.2, 0.55, ...
    diff(lexue) - 0.4, 10.6], ...
    'FaceColor', [0.94, 0.97, 1.0], 'EdgeColor', [0.48, 0.64, 0.84], ...
    'LineWidth', 1.4);
rectangle(ax, 'Position', [lexue(1) + 0.2, 9.45, ...
    diff(lexue) - 0.4, 1.7], ...
    'FaceColor', [0.18, 0.37, 0.66], 'EdgeColor', 'none');
text(ax, lexue(1) + 1.3, 10.3, '乐 学', ...
    'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', 'white', 'FontSize', 17);
text(ax, lexue(1) + 28.6, 10.3, '通知  50', ...
    'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', [1.0, 0.82, 0.25], 'FontSize', 13);
text(ax, lexue(1) + 1.4, 8.65, ...
    '选课倒计时  →  开始选课  →  我的课程', ...
    'FontName', cfg.render.fontName, 'Color', blue, ...
    'FontWeight', 'bold', 'FontSize', 12);

% Lucy River is the only end-of-journey water zone.
patch(ax, [lucy(1), lucy(2), lucy(2), lucy(1)], ...
    [0.2, 0.2, 6.4, 6.4], ...
    [0.34, 0.76, 0.90], 'EdgeColor', [0.10, 0.47, 0.67], ...
    'LineWidth', 1.5, 'FaceAlpha', 0.72);
text(ax, mean(lucy), 7.1, 'Lucy 河', 'HorizontalAlignment', 'center', ...
    'FontName', cfg.render.fontName, 'FontWeight', 'bold', ...
    'Color', [0.06, 0.35, 0.55], 'FontSize', 15);
end

function drawAlpacaShortcut(ax, platforms, cfg)
% The playable bridge is a clearly supported gameplay abstraction.
bridgeColor = [0.72, 0.15, 0.11];
edgeColor = [0.42, 0.08, 0.06];
for index = 1:size(platforms, 1)
    rect = platforms(index, :);
    rectangle(ax, 'Position', rect, 'FaceColor', bridgeColor, ...
        'EdgeColor', edgeColor, 'LineWidth', 2.0, 'Curvature', 0.02);
    deckTop = rect(2) + rect(4);
    railingTop = deckTop + 0.55;
    plot(ax, [rect(1), rect(1) + rect(3)], ...
        [railingTop, railingTop], '-', 'Color', edgeColor, ...
        'LineWidth', 1.8);
    for postX = linspace(rect(1), rect(1) + rect(3), 12)
        plot(ax, [postX, postX], [deckTop, railingTop], '-', ...
            'Color', edgeColor, 'LineWidth', 1.0);
    end
    supportXs = rect(1) + [0.8, rect(3) / 2, rect(3) - 0.8];
    for supportX = supportXs
        plot(ax, [supportX, supportX], [1.0, rect(2)], '-', ...
            'Color', [0.35, 0.20, 0.15], 'LineWidth', 2.5);
    end
end
first = platforms(1, :);
text(ax, first(1) + first(3) / 2, first(2) + first(4) + 1.0, ...
    '羊驼喷嚏捷径  →', 'HorizontalAlignment', 'center', ...
    'FontName', cfg.render.fontName, 'FontWeight', 'bold', ...
    'Color', edgeColor, 'FontSize', 10);
end
