function drawLexuePages(ax, lexue, cfg)
%DRAWLEXUEPAGES Rebuild both sanitized pages on their source pixel grids.

drawSelectionPage(ax, lexue, cfg);
drawHomePage(ax, lexue, cfg);
end

function drawSelectionPage(ax, lexue, cfg)
page = lexue.selectionPageRect;
pixels = lexue.pagePixelSize;
layout = lexue.layoutPixels;
blue = [0.17, 0.36, 0.73];
lightBlue = [0.47, 0.65, 0.91];

rectangle(ax, 'Position', page, 'FaceColor', [0.91, 0.94, 0.98], ...
    'EdgeColor', [0.56, 0.64, 0.75], 'LineWidth', 1.2);
drawPixelBox(ax, page, layout.selectionMain, pixels, blue, 'none', 0.97);

% Low-contrast geometry stands in for the photographed desktop beneath the
% blue overlay. It remains decorative and carries no source-image content.
keyboard = pixelRectToWorld(page, [670, 790, 1080, 390], pixels);
rectangle(ax, 'Position', keyboard, 'FaceColor', [0.19, 0.38, 0.74], ...
    'EdgeColor', [0.38, 0.55, 0.84], 'LineWidth', 0.7, ...
    'FaceAlpha', 0.34, 'Curvature', 0.04);
for row = 1:4
    y = keyboard(2) + 0.18 + row * 0.16;
    plot(ax, [keyboard(1) + 0.2, keyboard(1) + keyboard(3) - 0.2], ...
        [y, y], '-', 'Color', [0.48, 0.63, 0.88], 'LineWidth', 0.5);
end

drawPixelBox(ax, page, layout.selectionBottom, pixels, ...
    [1, 1, 1], 'none', 1.0);
drawPixelText(ax, page, [332, 70], pixels, 'Wisedu  |  选课', ...
    cfg, 9.0, 'white', 'bold', 'left');
drawPixelText(ax, page, [2435, 74], pixels, '退出', ...
    cfg, 7.0, 'white', 'normal', 'left');
drawPixelText(ax, page, [1317, 351], pixels, ...
    '大二及以上年级学生·第二轮预选·抽签', ...
    cfg, 10.5, 'white', 'bold', 'center');

status = pixelRectToWorld(page, layout.selectionStatus, pixels);
rectangle(ax, 'Position', status, 'FaceColor', [0.25, 0.67, 0.78], ...
    'EdgeColor', 'none', 'Curvature', 0.24);
text(ax, status(1) + status(3) / 2, status(2) + status(4) / 2, ...
    '进行中', 'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', 'FontName', cfg.render.fontName, ...
    'FontSize', 6.5, 'FontWeight', 'bold', 'Color', 'white');

drawSelectionTimeline(ax, page, layout.selectionTimeline, pixels, cfg);
drawCountdownFrame(ax, page, layout.countdownTiles, pixels, cfg, lightBlue);

drawPixelText(ax, page, [1094, 774], pixels, '预选', ...
    cfg, 9.0, 'white', 'bold', 'center');
drawPixelText(ax, page, [1094, 816], pixels, '选课模式', ...
    cfg, 6.5, [0.67, 0.78, 0.95], 'normal', 'center');
drawPixelText(ax, page, [1575, 774], pixels, '可选可退', ...
    cfg, 9.0, 'white', 'bold', 'center');
drawPixelText(ax, page, [1575, 816], pixels, '选课策略', ...
    cfg, 6.5, [0.67, 0.78, 0.95], 'normal', 'center');
drawPixelText(ax, page, [1088, 936], pixels, '匿名开始时间', ...
    cfg, 6.3, [0.78, 0.85, 0.98], 'normal', 'center');
drawPixelText(ax, page, [1570, 936], pixels, '匿名结束时间', ...
    cfg, 6.3, [0.78, 0.85, 0.98], 'normal', 'center');

drawSelectionUserCard(ax, page, layout.selectionUserCard, pixels, cfg);
button = pixelRectToWorld(page, layout.selectionStartButton, pixels);
rectangle(ax, 'Position', button, 'FaceColor', [0.05, 0.49, 0.86], ...
    'EdgeColor', [0.03, 0.35, 0.68], 'LineWidth', 0.9, ...
    'Curvature', 0.10);
text(ax, button(1) + button(3) / 2, button(2) + button(4) / 2, ...
    '开始选课', 'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'FontSize', 8.0, 'Color', 'white');

switchTab = pixelRectToWorld(page, layout.selectionSwitchTab, pixels);
rectangle(ax, 'Position', switchTab, 'FaceColor', [0.04, 0.45, 0.80], ...
    'EdgeColor', [0.02, 0.30, 0.60], 'LineWidth', 0.7, ...
    'Curvature', 0.16);
text(ax, switchTab(1) + switchTab(3) / 2, ...
    switchTab(2) + switchTab(4) / 2, sprintf('切\n换\n轮\n次'), ...
    'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
    'FontName', cfg.render.fontName, 'FontSize', 5.5, ...
    'FontWeight', 'bold', 'Color', 'white');

drawPixelText(ax, page, [330, 1537], pixels, '操作手册', ...
    cfg, 9.0, [0.20, 0.23, 0.28], 'bold', 'left');
drawPixelText(ax, page, [1475, 1537], pixels, '通知公告', ...
    cfg, 9.0, [0.20, 0.23, 0.28], 'bold', 'left');
rectangle(ax, 'Position', page, 'FaceColor', 'none', ...
    'EdgeColor', [0.45, 0.56, 0.70], 'LineWidth', 1.2);
end

function drawSelectionTimeline(ax, page, pixelRect, pixels, cfg)
timeline = pixelRectToWorld(page, pixelRect, pixels);
lineX = timeline(1) + 0.35 * timeline(3);
plot(ax, [lineX, lineX], ...
    [timeline(2) + 0.15 * timeline(4), ...
     timeline(2) + 0.85 * timeline(4)], '-', ...
    'Color', [0.87, 0.92, 1.0], 'LineWidth', 1.0);
for fraction = [0.15, 0.85]
    y = timeline(2) + fraction * timeline(4);
    plot(ax, lineX, y, 'o', 'MarkerSize', 6, ...
        'MarkerFaceColor', [0.33, 0.55, 0.88], ...
        'MarkerEdgeColor', 'white', 'LineWidth', 0.9);
end
text(ax, timeline(1) - 0.08, timeline(2) + 0.50 * timeline(4), ...
    sprintf('第二轮预选\n抽签'), 'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'middle', 'FontName', cfg.render.fontName, ...
    'FontSize', 6.0, 'FontWeight', 'bold', 'Color', 'white');
text(ax, timeline(1) + 0.55 * timeline(3), ...
    timeline(2) + 0.79 * timeline(4), '匿名开始', ...
    'FontName', cfg.render.fontName, 'FontSize', 5.2, 'Color', 'white');
text(ax, timeline(1) + 0.55 * timeline(3), ...
    timeline(2) + 0.09 * timeline(4), '匿名结束', ...
    'FontName', cfg.render.fontName, 'FontSize', 5.2, 'Color', 'white');
end

function drawCountdownFrame(ax, page, tilePixels, pixels, cfg, color)
tiles = pixelRectToWorld(page, tilePixels, pixels);
for index = 1:size(tiles, 1)
    rectangle(ax, 'Position', tiles(index, :), ...
        'FaceColor', color, 'EdgeColor', [0.56, 0.70, 0.93], ...
        'LineWidth', 0.6, 'FaceAlpha', 0.50, 'Curvature', 0.10);
end
drawPixelText(ax, page, [1227, 578], pixels, '天', ...
    cfg, 7.0, 'white', 'normal', 'center');
drawPixelText(ax, page, [1465, 578], pixels, '小时', ...
    cfg, 6.2, 'white', 'normal', 'center');
drawPixelText(ax, page, [1722, 578], pixels, '分钟', ...
    cfg, 6.2, 'white', 'normal', 'center');
end

function drawSelectionUserCard(ax, page, pixelRect, pixels, cfg)
card = pixelRectToWorld(page, pixelRect, pixels);
rectangle(ax, 'Position', card, 'FaceColor', [1, 1, 1], ...
    'EdgeColor', [0.92, 0.92, 0.94], 'LineWidth', 0.8, ...
    'Curvature', 0.03);
avatar = pixelRectToWorld(page, [1950, 208, 132, 132], pixels);
rectangle(ax, 'Position', avatar, 'FaceColor', [0.88, 0.92, 0.98], ...
    'EdgeColor', [0.72, 0.80, 0.92], 'LineWidth', 0.6, ...
    'Curvature', 0.45);
text(ax, avatar(1) + avatar(3) / 2, avatar(2) + avatar(4) / 2, ...
    '人', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
    'FontName', cfg.render.fontName, 'FontSize', 9, ...
    'FontWeight', 'bold', 'Color', [0.37, 0.56, 0.83]);
drawPixelText(ax, page, [2100, 252], pixels, '欢迎你  匿名同学', ...
    cfg, 7.2, [0.20, 0.22, 0.26], 'bold', 'left');
drawPixelText(ax, page, [2100, 305], pixels, '学院信息已隐去', ...
    cfg, 5.7, [0.34, 0.36, 0.40], 'normal', 'left');
drawPixelText(ax, page, [2100, 350], pixels, '学年信息已隐去', ...
    cfg, 5.7, [0.34, 0.36, 0.40], 'normal', 'left');
drawPixelText(ax, page, [2010, 925], pixels, '切换语言：  简体中文', ...
    cfg, 5.8, [0.25, 0.27, 0.30], 'bold', 'left');
end

function drawHomePage(ax, lexue, cfg)
page = lexue.homePageRect;
pixels = lexue.pagePixelSize;
layout = lexue.layoutPixels;
nav = [0.20, 0.31, 0.52];
brand = [0.28, 0.42, 0.66];
linkBlue = [0.16, 0.36, 0.62];

rectangle(ax, 'Position', page, 'FaceColor', [1, 1, 1], ...
    'EdgeColor', [0.62, 0.69, 0.78], 'LineWidth', 1.2);
drawPixelBox(ax, page, layout.homeTopNav, pixels, nav, 'none', 1.0);
drawPixelBox(ax, page, layout.homeBrandNav, pixels, brand, 'none', 1.0);

for lineIndex = 0:2
    p1 = pixelPoint(page, [215, 35 + 17 * lineIndex], pixels);
    p2 = pixelPoint(page, [262, 35 + 17 * lineIndex], pixels);
    plot(ax, [p1(1), p2(1)], [p1(2), p2(2)], '-', ...
        'Color', 'white', 'LineWidth', 1.6);
end
drawPixelText(ax, page, [2245, 65], pixels, ...
    '搜索   通知 50   匿名用户', cfg, 6.2, 'white', 'normal', 'left');
drawPixelText(ax, page, [330, 174], pixels, '乐 学', ...
    cfg, 11.0, 'white', 'bold', 'left');
drawPixelText(ax, page, [2320, 174], pixels, '简体中文', ...
    cfg, 6.2, 'white', 'normal', 'left');

drawHomeTutorial(ax, page, layout.homeTutorial, pixels, cfg, linkBlue);
drawHomeProfile(ax, page, layout.homeProfileCard, pixels, cfg);
drawHomeNotice(ax, page, layout.homeNoticeCard, pixels, cfg);
drawHomeCourses(ax, page, layout, pixels, cfg, linkBlue);

badge = pixelRectToWorld(page, [2298, 15, 42, 42], pixels);
rectangle(ax, 'Position', badge, 'FaceColor', [0.91, 0.22, 0.15], ...
    'EdgeColor', 'none', 'Curvature', 0.16);
text(ax, badge(1) + badge(3) / 2, badge(2) + badge(4) / 2, '50', ...
    'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
    'FontName', cfg.render.fontName, 'FontSize', 5.0, ...
    'FontWeight', 'bold', 'Color', 'white');
rectangle(ax, 'Position', page, 'FaceColor', 'none', ...
    'EdgeColor', [0.45, 0.56, 0.70], 'LineWidth', 1.2);
end

function drawHomeTutorial(ax, page, pixelRect, pixels, cfg, linkBlue)
area = pixelRectToWorld(page, pixelRect, pixels);
drawPixelText(ax, page, [224, 365], pixels, '乐学使用教程', ...
    cfg, 10.0, linkBlue, 'normal', 'left');
rows = {'乐学简易使用教程·学生版', ...
    '乐学简易使用教程·教师版', ...
    '教师快速创建教学班群', ...
    '教师端建课与管理指南', ...
    '安全考试浏览器说明', ...
    '平台测验功能介绍', ...
    '教学过程平台操作手册'};
rowY = [455, 530, 605, 680, 755, 830, 905];
for index = 1:numel(rows)
    icon = pixelRectToWorld(page, [224, rowY(index) - 29, 34, 42], pixels);
    rectangle(ax, 'Position', icon, 'FaceColor', [0.91, 0.19, 0.16], ...
        'EdgeColor', [0.72, 0.12, 0.10], 'LineWidth', 0.5);
    drawPixelText(ax, page, [280, rowY(index)], pixels, rows{index}, ...
        cfg, 6.2, linkBlue, 'normal', 'left');
end
plot(ax, [area(1), area(1) + area(3)], [area(2), area(2)], '-', ...
    'Color', [0.86, 0.89, 0.93], 'LineWidth', 0.6);
end

function drawHomeProfile(ax, page, pixelRect, pixels, cfg)
card = pixelRectToWorld(page, pixelRect, pixels);
rectangle(ax, 'Position', card, 'FaceColor', [1, 1, 1], ...
    'EdgeColor', [0.70, 0.78, 0.88], 'LineWidth', 0.7);
header = pixelRectToWorld(page, [2075, 296, 560, 87], pixels);
rectangle(ax, 'Position', header, 'FaceColor', [0.89, 0.93, 0.98], ...
    'EdgeColor', [0.70, 0.78, 0.88], 'LineWidth', 0.5);
drawPixelText(ax, page, [2110, 353], pixels, '已登录用户', ...
    cfg, 7.0, [0.16, 0.35, 0.60], 'normal', 'left');
avatar = pixelRectToWorld(page, [2122, 414, 110, 110], pixels);
rectangle(ax, 'Position', avatar, 'FaceColor', [0.62, 0.62, 0.62], ...
    'EdgeColor', 'none', 'Curvature', 0.48);
drawPixelText(ax, page, [2260, 474], pixels, '匿名用户', ...
    cfg, 8.2, [0.24, 0.24, 0.25], 'bold', 'left');
drawPixelText(ax, page, [2260, 548], pixels, '访问记录已隐去', ...
    cfg, 5.7, [0.31, 0.31, 0.32], 'normal', 'left');
end

function drawHomeNotice(ax, page, pixelRect, pixels, cfg)
card = pixelRectToWorld(page, pixelRect, pixels);
rectangle(ax, 'Position', card, 'FaceColor', [1, 1, 1], ...
    'EdgeColor', [0.70, 0.78, 0.88], 'LineWidth', 0.7);
drawPixelText(ax, page, [2115, 740], pixels, '提示：', ...
    cfg, 7.0, [0.92, 0.20, 0.16], 'bold', 'left');
drawPixelText(ax, page, [2115, 825], pixels, ...
    sprintf('新版课堂已上线\n教学资源请按需迁移\n推荐使用现代浏览器'), ...
    cfg, 5.8, [0.27, 0.28, 0.30], 'bold', 'left');
end

function drawHomeCourses(ax, page, layout, pixels, cfg, linkBlue)
panel = pixelRectToWorld(page, layout.homeCoursePanel, pixels);
rectangle(ax, 'Position', panel, 'FaceColor', [1, 1, 1], ...
    'EdgeColor', [0.69, 0.77, 0.88], 'LineWidth', 0.7);
header = pixelRectToWorld(page, layout.homeCourseHeader, pixels);
rectangle(ax, 'Position', header, 'FaceColor', [0.89, 0.93, 0.98], ...
    'EdgeColor', [0.69, 0.77, 0.88], 'LineWidth', 0.5);
drawPixelText(ax, page, [248, 1137], pixels, '我的课程', ...
    cfg, 10.0, linkBlue, 'normal', 'left');

course = pixelRectToWorld(page, layout.homeCourseCard, pixels);
rectangle(ax, 'Position', course, 'FaceColor', [1, 1, 1], ...
    'EdgeColor', [0.78, 0.80, 0.82], 'LineWidth', 0.6);
drawPixelText(ax, page, [312, 1273], pixels, '匿名课程', ...
    cfg, 7.0, linkBlue, 'normal', 'left');
drawPixelText(ax, page, [260, 1360], pixels, '教师信息已隐去', ...
    cfg, 5.5, [0.43, 0.44, 0.46], 'normal', 'left');

category = pixelRectToWorld(page, layout.homeCategoryHeader, pixels);
rectangle(ax, 'Position', category, 'FaceColor', [0.89, 0.93, 0.98], ...
    'EdgeColor', [0.69, 0.77, 0.88], 'LineWidth', 0.5);
drawPixelText(ax, page, [248, 1630], pixels, '课程类别', ...
    cfg, 9.0, linkBlue, 'normal', 'left');
end

function drawPixelBox(ax, page, pixelRect, pixels, faceColor, edgeColor, alpha)
rect = pixelRectToWorld(page, pixelRect, pixels);
rectangle(ax, 'Position', rect, 'FaceColor', faceColor, ...
    'EdgeColor', edgeColor, 'LineWidth', 0.6, 'FaceAlpha', alpha);
end

function drawPixelText(ax, page, pixelXY, pixels, label, cfg, ...
        fontSize, color, weight, alignment)
point = pixelPoint(page, pixelXY, pixels);
text(ax, point(1), point(2), label, ...
    'HorizontalAlignment', alignment, 'VerticalAlignment', 'middle', ...
    'FontName', cfg.render.fontName, 'FontSize', fontSize, ...
    'FontWeight', weight, 'Color', color, 'Interpreter', 'none');
end

function point = pixelPoint(page, pixelXY, pixels)
scale = page(3) / pixels(1);
point = [page(1) + pixelXY(1) * scale, ...
    page(2) + (pixels(2) - pixelXY(2)) * scale];
end
