function drawContinuousBackground(ax, world, cfg)
%DRAWCONTINUOUSBACKGROUND Draw one uninterrupted, readable campus strip.

ink = cfg.presentation.colors.ink;
northLake = world.regions(strcmp({world.regions.id}, 'northLake')).xRange;
traffic = world.regions(strcmp({world.regions.id}, 'traffic')).xRange;
lexue = world.regions(strcmp({world.regions.id}, 'lexue')).xRange;
lucy = world.regions(strcmp({world.regions.id}, 'lucy')).xRange;

% MATLAB origin: the graph remains part of the world rather than a title card.
patch(ax, [0, 12, 12, 0], [0, 0, 11.2, 11.2], ...
    [0.93, 0.97, 0.94], 'EdgeColor', 'none');
for gridX = 1:1.5:11.5
    plot(ax, [gridX, gridX], [1.0, 10.8], ':', ...
        'Color', [0.66, 0.77, 0.71], 'LineWidth', 0.75);
end
for gridY = 1:1.5:10.8
    plot(ax, [0.7, 11.5], [gridY, gridY], ':', ...
        'Color', [0.66, 0.77, 0.71], 'LineWidth', 0.75);
end
plot(ax, [1.0, 1.0], [1.0, 9.4], '-', 'Color', [0.24, 0.34, 0.38], ...
    'LineWidth', 1.8);
plot(ax, [0.8, 11.2], [1.0, 1.0], '-', 'Color', [0.24, 0.34, 0.38], ...
    'LineWidth', 1.8);
x = linspace(1.1, 11.0, 70);
y = 5.0 + 1.1 * sin(0.9 * x) + 0.035 * (x - 6) .^ 2;
plot(ax, x, y, '-', 'Color', [0.76, 0.22, 0.20], 'LineWidth', 2.2);
text(ax, 1.5, 10.2, 'MATLAB 坐标轴入口', ...
    'FontName', cfg.render.fontName, 'FontWeight', 'bold', ...
    'Color', ink, 'FontSize', 14);
text(ax, 1.5, 9.55, '从一条曲线，走进一整座校园', ...
    'FontName', cfg.render.fontName, 'Color', [0.29, 0.43, 0.36], ...
    'FontSize', 10.5);

% North Lake: the two plates are derived from the checked real topology and
% photographs. The west plate carries the supported red bridge; the east
% plate deliberately returns to open water and tree-lined bank.
drawTexturePlate(ax, [northLake(1), 0.15, 26.0, 12.65], ...
    cfg.assets.northLakeWest, cfg.render.backgroundTextureStride);
drawTexturePlate(ax, [northLake(1) + 26.0, 0.15, 26.0, 12.65], ...
    cfg.assets.northLakeEast, cfg.render.backgroundTextureStride);
drawSceneLabel(ax, northLake(1) + 4.0, 10.75, ...
    '北湖 · 动物借道', 'WEST SHORE / OPEN WATER', cfg);
drawAlpacaShortcut(ax, world.mechanic.animals.shortcutPlatforms, cfg);

% The complete privacy-checked page keeps its native aspect and grid.
drawNetworkPage(ax, world.mechanic.network.pageRect, ...
    cfg.assets.loginImage);

% The southward chapter uses independently checked campus anchors. The
% sports/defence plate and museum plate are adjacent narrative backdrops,
% not an assertion that these buildings stand next to one another in reality.
drawTexturePlate(ax, [traffic(1), 0.15, 27.0, 12.65], ...
    cfg.assets.sportsDefense, cfg.render.backgroundTextureStride);
drawTexturePlate(ax, [traffic(1) + 27.0, 0.15, 25.0, 12.65], ...
    cfg.assets.museum, cfg.render.backgroundTextureStride);
patch(ax, [traffic(1), traffic(2), traffic(2), traffic(1)], ...
    [0.65, 0.65, 4.1, 4.1], ...
    [0.76, 0.72, 0.63], 'EdgeColor', 'none', 'FaceAlpha', 0.48);
crosswalk = world.mechanic.traffic.crosswalk;
rectangle(ax, 'Position', [crosswalk(1) - 0.15, 0.65, ...
    crosswalk(3) + 0.30, 4.20], ...
    'FaceColor', [0.34, 0.38, 0.41], 'EdgeColor', [0.20, 0.23, 0.25], ...
    'LineWidth', 1.2);
for stripeY = 1.08:0.40:2.48
    rectangle(ax, 'Position', [crosswalk(1) + 0.08, stripeY, ...
        crosswalk(3) - 0.16, 0.17], ...
        'FaceColor', [0.94, 0.94, 0.92], 'EdgeColor', 'none');
end
roadCentre = crosswalk(1) + crosswalk(3) / 2;
plot(ax, [roadCentre, roadCentre], [2.85, 4.65], '--', ...
    'Color', [0.95, 0.92, 0.65], 'LineWidth', 1.4);
for supportX = traffic(1) + [12, 24, 33, 44]
    plot(ax, [supportX, supportX], [4.1, 6.0], '-', ...
        'Color', [0.31, 0.35, 0.38], 'LineWidth', 3.0);
end
drawSceneLabel(ax, traffic(1) + 1.0, 10.75, ...
    '体育馆 · 国防装备展示', 'SPORT / CAMPUS MEMORY', cfg);
drawSceneLabel(ax, traffic(1) + 28.0, 10.75, ...
    '文博空间 · 校史记忆', 'MUSEUM / CULTURE', cfg);
drawCampusEmblemSign(ax, [traffic(1) + 43.4, 7.45, 3.1, 3.4], ...
    cfg.assets.bitEmblem, cfg);

% A quiet landscaped backing keeps the web-page chapter from falling back
% to the old empty grey world. The source-modelled pages are still drawn at
% their frozen rectangles and remain the dominant layer.
patch(ax, [lexue(1), lexue(2), lexue(2), lexue(1)], ...
    [0.15, 0.15, 12.8, 12.8], [0.77, 0.88, 0.78], ...
    'EdgeColor', 'none');
patch(ax, [lexue(1), lexue(2), lexue(2), lexue(1)], ...
    [0.15, 0.15, 4.4, 4.4], [0.64, 0.73, 0.55], ...
    'EdgeColor', 'none');
for treeX = lexue(1) + 1.2:3.4:lexue(2) - 1
    plot(ax, treeX, 9.5 + 0.35 * mod(round(treeX), 3), 'o', ...
        'MarkerSize', 25, 'MarkerFaceColor', [0.29, 0.50, 0.27], ...
        'MarkerEdgeColor', [0.14, 0.29, 0.16], 'LineWidth', 1.0);
end

% Both pages preserve their respective 2852-by-1654 source grids. Personal
% fields are replaced in-place rather than being moved or reflowed.
drawLexuePages(ax, world.mechanic.lexue, cfg);

% Lucy River is the only end-of-journey water zone.
patch(ax, [lucy(1), lucy(2), lucy(2), lucy(1)], ...
    [0.2, 0.2, 6.4, 6.4], ...
    [0.34, 0.76, 0.90], 'EdgeColor', [0.10, 0.47, 0.67], ...
    'LineWidth', 1.5, 'FaceAlpha', 0.72);
text(ax, mean(lucy), 7.1, 'Lucy 河', 'HorizontalAlignment', 'center', ...
    'FontName', cfg.render.fontName, 'FontWeight', 'bold', ...
    'Color', [0.06, 0.35, 0.55], 'FontSize', 15);
end

function drawTexturePlate(ax, rect, imagePath, stride)
rgb = imread(imagePath);
stride = max(1, round(stride));
rgb = rgb(1:stride:end, 1:stride:end, :);
x = rect(1) + [0, rect(3); 0, rect(3)];
y = rect(2) + [0, 0; rect(4), rect(4)];
surface(ax, x, y, zeros(2), 'CData', flipud(rgb), ...
    'FaceColor', 'texturemap', 'EdgeColor', 'none');
end

function drawSceneLabel(ax, x, y, titleText, kicker, cfg)
text(ax, x, y, {titleText, kicker}, ...
    'FontName', cfg.render.fontName, 'FontWeight', 'bold', ...
    'FontSize', 12.5, 'Color', [0.97, 0.96, 0.88], ...
    'BackgroundColor', [0.10, 0.18, 0.16], 'Margin', 6, ...
    'VerticalAlignment', 'top');
end

function drawCampusEmblemSign(ax, rect, imagePath, cfg)
postColor = [0.23, 0.20, 0.14];
plot(ax, [rect(1) + 0.35, rect(1) + 0.35], ...
    [rect(2) - 1.45, rect(2)], '-', 'Color', postColor, 'LineWidth', 5.0);
plot(ax, [rect(1) + rect(3) - 0.35, rect(1) + rect(3) - 0.35], ...
    [rect(2) - 1.45, rect(2)], '-', 'Color', postColor, 'LineWidth', 5.0);
rectangle(ax, 'Position', rect, 'FaceColor', [0.96, 0.93, 0.82], ...
    'EdgeColor', postColor, 'LineWidth', 2.2, 'Curvature', 0.06);
rgb = imread(imagePath);
textureRect = [rect(1) + 0.62, rect(2) + 0.68, ...
    rect(3) - 1.24, rect(3) - 1.24];
x = textureRect(1) + [0, textureRect(3); 0, textureRect(3)];
y = textureRect(2) + [0, 0; textureRect(4), textureRect(4)];
surface(ax, x, y, 0.1 * ones(2), 'CData', flipud(rgb), ...
    'FaceColor', 'texturemap', 'EdgeColor', 'none');
text(ax, rect(1) + rect(3) / 2, rect(2) + 0.32, '北京理工大学', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'FontSize', 7.5, 'Color', [0.34, 0.19, 0.11]);
end

function drawAlpacaShortcut(ax, platforms, cfg)
% The playable bridge is a clearly supported gameplay abstraction.
bridgeColor = [0.72, 0.15, 0.11];
edgeColor = [0.42, 0.08, 0.06];
for index = 1:size(platforms, 1)
    rect = platforms(index, :);
    rectangle(ax, 'Position', rect, 'FaceColor', bridgeColor, ...
        'EdgeColor', edgeColor, 'LineWidth', 2.0, 'Curvature', 0.02);
    deckTop = rect(2) + rect(4);
    railingTop = deckTop + 0.55;
    plot(ax, [rect(1), rect(1) + rect(3)], ...
        [railingTop, railingTop], '-', 'Color', edgeColor, ...
        'LineWidth', 1.8);
    for postX = linspace(rect(1), rect(1) + rect(3), 12)
        plot(ax, [postX, postX], [deckTop, railingTop], '-', ...
            'Color', edgeColor, 'LineWidth', 1.0);
    end
    % Keep the first support away from the alpaca launch pocket so it cannot
    % be mistaken for a blocking wall, while preserving three clear supports.
    supportXs = rect(1) + [3.2, 0.55 * rect(3), rect(3) - 0.9];
    for supportX = supportXs
        plot(ax, [supportX, supportX], [1.0, rect(2)], '-', ...
            'Color', [0.35, 0.20, 0.15], 'LineWidth', 2.5);
    end
end

first = platforms(1, :);
text(ax, first(1) + first(3) / 2, first(2) + first(4) + 1.0, ...
    '羊驼喷嚏捷径  →', 'HorizontalAlignment', 'center', ...
    'FontName', cfg.render.fontName, 'FontWeight', 'bold', ...
    'Color', edgeColor, 'FontSize', 10);
end

function drawNetworkPage(ax, pageRect, imagePath)
rgb = imread(imagePath);
x = pageRect(1) + [0, pageRect(3); 0, pageRect(3)];
y = pageRect(2) + [0, 0; pageRect(4), pageRect(4)];
surface(ax, x, y, zeros(2), 'CData', flipud(rgb), ...
    'FaceColor', 'texturemap', 'EdgeColor', 'none');
rectangle(ax, 'Position', pageRect, 'FaceColor', 'none', ...
    'EdgeColor', [0.18, 0.38, 0.58], 'LineWidth', 1.5);
end
