function handles = initializeContinuousHandles(ax, world, cfg, campusOnly)
%INITIALIZECONTINUOUSHANDLES Create reusable graphics for the v3 world.

handles = struct();
if nargin>=4 && campusOnly
    handles = initializeBusHandles(handles, ax, world, cfg);
elseif strcmp(cfg.render.activeSegment, 'world')
    % Prepare every pre-flight interaction before control begins. Measured
    % camera-triggered creation caused 0.2--0.9 s hitches during live play.
    % Include the bus now so landing never rebuilds the scene.
    handles = initializeAnimalHandles(ax, world, cfg);
    handles = initializeTeaHandles(handles, ax, world, cfg);
    handles = initializeNetworkHandles(handles, ax, world, cfg);
    handles = initializeTrafficHandles(handles, ax, world, cfg);
    handles = initializeBicycleHandles(handles, ax, world, cfg);
    handles = initializeBusHandles(handles, ax, world, cfg);
end
end

function handles = initializeAnimalHandles(ax, ~, cfg)
% The RGBA alpaca is loaded only while its camera pocket is visible.
handles.alpacaSprite = gobjects(1);
handles.alpacaWarning = text(ax, 0, 0, '抬腿！', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', [0.76, 0.22, 0.18], ...
    'Visible', 'off');
handles.alpacaKickLines = plot(ax, nan, nan, '-', ...
    'Color', [0.80, 0.24, 0.12], 'LineWidth', 2.0, 'Visible', 'off');
handles.alpacaLabel = text(ax, 0, 0, '羊驼 · 身后触发后踢', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', [0.38, 0.22, 0.12], ...
    'FontSize', 9, 'Visible', 'off');

handles.peacockTail = patch(ax, nan, nan, [0.10, 0.61, 0.47], ...
    'EdgeColor', [0.04, 0.25, 0.23], 'LineWidth', 1.4, ...
    'FaceAlpha', 0.92, 'Visible', 'off');
handles.peacockEyespots = plot(ax, nan, nan, 'o', ...
    'LineStyle', 'none', 'MarkerSize', 4.5, ...
    'MarkerFaceColor', [0.93, 0.71, 0.13], ...
    'MarkerEdgeColor', [0.04, 0.23, 0.39], 'LineWidth', 0.8, ...
    'Visible', 'off');
handles.peacockBody = patch(ax, nan, nan, [0.08, 0.42, 0.58], ...
    'EdgeColor', [0.03, 0.18, 0.29], 'LineWidth', 1.3, ...
    'Visible', 'off');
handles.peacockNeck = plot(ax, nan, nan, '-', ...
    'Color', [0.05, 0.37, 0.55], 'LineWidth', 5.0, 'Visible', 'off');
handles.peacockHead = plot(ax, nan, nan, 'o', ...
    'MarkerSize', 8.0, 'MarkerFaceColor', [0.08, 0.42, 0.58], ...
    'MarkerEdgeColor', [0.03, 0.18, 0.29], 'LineWidth', 1.0, ...
    'Visible', 'off');
handles.peacockBeak = patch(ax, nan, nan, [0.90, 0.63, 0.12], ...
    'EdgeColor', [0.48, 0.29, 0.05], 'LineWidth', 0.8, ...
    'Visible', 'off');
handles.peacockCrest = plot(ax, nan, nan, '-', ...
    'Color', [0.04, 0.27, 0.41], 'LineWidth', 1.2, 'Visible', 'off');
handles.peacockFeet = plot(ax, nan, nan, '-', ...
    'Color', [0.48, 0.34, 0.13], 'LineWidth', 1.2, 'Visible', 'off');
handles.peacockLabel = text(ax, 0, 0, '孔雀开屏 · 弹回高桥', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', [0.08, 0.31, 0.30], ...
    'FontSize', 8.5, 'Visible', 'off');
end

function handles = initializeTeaHandles(handles, ax, world, cfg)
teaCount = numel(world.mechanic.tea);
handles.tea = gobjects(teaCount, 1);
for index = 1:teaCount
    handles.tea(index) = createTeaSprite(ax, cfg.assets.teaSprite, ...
        cfg.render.teaTextureStride, cfg.tea);
end
end

function handles = initializeNetworkHandles(handles, ax, world, cfg)
pageRect = world.mechanic.network.pageRect;
handles.networkTimeoutPage = createNetworkPageSurface(ax, pageRect, ...
    cfg.assets.networkTimeoutImage, cfg.render.networkStateTextureStride);
handles.networkSuccessPage = createNetworkPageSurface(ax, pageRect, ...
    cfg.assets.networkAuthenticatedImage, ...
    cfg.render.networkStateTextureStride);
handles.networkLoadingRing = plot(ax, nan, nan, 'o', ...
    'LineStyle', 'none', 'MarkerSize', 5.5, ...
    'MarkerFaceColor', [0.14, 0.58, 0.84], ...
    'MarkerEdgeColor', [0.04, 0.27, 0.46], 'Visible', 'off');
handles.networkLoadingText = text(ax, 0, 0, '正在连接校园网…', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'FontSize', 10.5, ...
    'Color', [0.06, 0.30, 0.50], 'BackgroundColor', [0.96, 0.98, 1.0], ...
    'Margin', 5, 'Visible', 'off');
handles.networkSuccessStatus = text(ax, 0, 0, '', ...
    'HorizontalAlignment', 'left', 'VerticalAlignment', 'middle', ...
    'FontName', cfg.render.fontName, 'FontWeight', 'bold', ...
    'FontSize', 7.8, 'Color', [0.08, 0.12, 0.18], ...
    'Interpreter', 'none', 'Visible', 'off');

handles.networkFields = gobjects(2, 1);
handles.networkFieldLabels = gobjects(2, 1);
for index = 1:2
    handles.networkFields(index) = rectangle(ax, ...
        'Position', [0, 0, 1, 1], 'FaceColor', [0.90, 0.94, 0.98], ...
        'EdgeColor', [0.19, 0.29, 0.42], 'LineWidth', 1.6, ...
        'Curvature', 0.06, 'FaceAlpha', 0.34, 'Visible', 'off');
    handles.networkFieldLabels(index) = text(ax, 0, 0, '', ...
        'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
        'FontWeight', 'bold', 'Color', [0.12, 0.22, 0.34], ...
        'Interpreter', 'none', 'Visible', 'off');
end
handles.networkCheckbox = rectangle(ax, 'Position', [0, 0, 1, 1], ...
    'FaceColor', [0.94, 0.96, 0.98], 'EdgeColor', [0.19, 0.29, 0.42], ...
    'LineWidth', 1.5, 'FaceAlpha', 0.42, 'Visible', 'off');
handles.networkCheckboxLabel = text(ax, 0, 0, '', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'FontSize', 8.5, 'Visible', 'off');
handles.networkLogin = rectangle(ax, 'Position', [0, 0, 1, 1], ...
    'FaceColor', [0.67, 0.76, 0.82], 'EdgeColor', [0.18, 0.30, 0.38], ...
    'LineWidth', 1.7, 'Curvature', 0.10, 'FaceAlpha', 0.42, ...
    'Visible', 'off');
handles.networkLoginLabel = text(ax, 0, 0, '', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', 'white', 'Visible', 'off');
handles.networkGate = rectangle(ax, 'Position', [0, 0, 1, 1], ...
    'FaceColor', [0.88, 0.25, 0.21], 'EdgeColor', [0.42, 0.08, 0.07], ...
    'LineWidth', 1.8, 'FaceAlpha', 0.70, 'Visible', 'off');
handles.networkSelfService = rectangle(ax, 'Position', [0, 0, 1, 1], ...
    'FaceColor', [0.20, 0.66, 0.83], 'EdgeColor', [0.05, 0.33, 0.50], ...
    'LineWidth', 1.8, 'Curvature', 0.08, 'FaceAlpha', 0.42, ...
    'Visible', 'off');
handles.networkSelfServiceLabel = text(ax, 0, 0, '自助服务', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', [0.05, 0.27, 0.40], 'Visible', 'off');
end

function handles = initializeTrafficHandles(handles, ax, world, cfg)
traffic = world.mechanic.traffic;
handles.climbRungs = gobjects(traffic.climbPressesRequired, 1);
for index = 1:numel(handles.climbRungs)
    handles.climbRungs(index) = plot(ax, nan, nan, '-', ...
        'Color', [0.79, 0.82, 0.80], 'LineWidth', 3.0, 'Visible', 'off');
end
handles.climbProgress = text(ax, 0, 0, '', 'HorizontalAlignment', 'center', ...
    'FontName', cfg.render.fontName, 'FontWeight', 'bold', ...
    'Color', [0.96, 0.95, 0.86], 'BackgroundColor', [0.15, 0.20, 0.21], ...
    'Margin', 4, 'Visible', 'off');
handles.upperBridgePlatforms = gobjects(size(traffic.upperBridgePlatforms, 1), 1);
for index = 1:numel(handles.upperBridgePlatforms)
    handles.upperBridgePlatforms(index) = rectangle(ax, ...
        'Position', traffic.upperBridgePlatforms(index, :), ...
        'FaceColor', [0.70, 0.12, 0.10], 'EdgeColor', [0.35, 0.05, 0.04], ...
        'LineWidth', 1.5, 'Visible', 'off');
end

handles.signalHousing=gobjects(2,1);
handles.signalLights=gobjects(3,2);
handles.signalLabel=gobjects(2,1);
for side=1:2
signalX = traffic.signalX(side);
handles.signalHousing(side) = rectangle(ax, ...
    'Position', [signalX - 0.43, 2.60, .86, 2.1], ...
    'FaceColor', [0.16, 0.20, 0.22], 'EdgeColor', [0.04, 0.06, 0.07], ...
    'LineWidth', 1.5, 'Curvature', 0.15, 'Visible', 'off');
for index = 1:3
    handles.signalLights(index,side) = rectangle(ax, ...
        'Position',[signalX-.32,4.02-(index-1)*.68,.64,.64], ...
        'Curvature',[1 1],'FaceColor',[.27 .29 .30], ...
        'EdgeColor',[.06 .07 .08],'LineWidth',1, ...
        'Visible', 'off');
end
handles.signalLabel(side) = text(ax, signalX, 4.92, '', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'FontSize',8, 'Color', [1 1 .94], ...
    'BackgroundColor',[.12 .18 .22],'Visible', 'off');
end
handles.routeLabel = text(ax, traffic.climbZone(1) + 2.2, 8.7, '', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', [0.12, 0.18, 0.22], 'Visible', 'off');
handles.pedestrianBarrier = rectangle(ax, 'Position', [0, 0, 1, 1], ...
    'FaceColor', [0.88, 0.26, 0.20], 'EdgeColor', [0.42, 0.08, 0.06], ...
    'LineWidth', 1.7, 'Curvature', 0.08, 'Visible', 'off');
handles.pedestrianBarrierLabel = text(ax, 0, 0, '请等行人绿灯', ...
    'HorizontalAlignment', 'right', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'FontSize', 8.5, ...
    'Color', [0.52, 0.10, 0.08], 'Visible', 'off');

carCount = size(traffic.carData, 1);
% A whole traffic stream needs three HG objects, not three objects per car.
% Physics still keeps one rectangle per car; only their display is batched.
handles.cars = patch(ax, nan(4, carCount), nan(4, carCount), ...
    [0.88, 0.29, 0.20], 'EdgeColor', [0.35, 0.08, 0.06], ...
    'LineWidth', 1.6, 'Visible', 'off');
handles.carWindows = patch(ax, nan(4, carCount), nan(4, carCount), ...
    [0.67, 0.86, 0.91], 'EdgeColor', [0.20, 0.32, 0.37], ...
    'LineWidth', 0.9, 'Visible', 'off');
handles.carWheels = plot(ax, nan, nan, 'o', 'LineStyle', 'none', ...
    'MarkerSize', 6, 'MarkerFaceColor', [0.10, 0.12, 0.13], ...
    'MarkerEdgeColor', [0.03, 0.04, 0.05], 'Visible', 'off');
crowdCount = size(traffic.crowdData, 1);
crowdColours = [0.56, 0.48, 0.76; 0.30, 0.61, 0.67; 0.83, 0.51, 0.38];
crowdColours = crowdColours(mod((0:crowdCount - 1)', 3) + 1, :);
crowdFaces = reshape(1:(4 * crowdCount), 4, [])';
handles.crowd = patch(ax, 'Vertices', zeros(4 * crowdCount, 2), ...
    'Faces', crowdFaces, 'FaceVertexCData', crowdColours, ...
    'FaceColor', 'flat', 'EdgeColor', [0.22, 0.16, 0.39], ...
    'LineWidth', 1.1, 'Visible', 'off');
handles.crowdLegs = plot(ax, nan, nan, '-', ...
    'Color', [0.22 0.27 0.30], 'LineWidth', 3, 'Visible', 'off');
handles.crowdHeads = patch(ax, nan(24, crowdCount), ...
    nan(24, crowdCount), [0.91 0.73 0.58], ...
    'EdgeColor', [0.31 0.23 0.19], 'LineWidth', 0.8, 'Visible', 'off');
end

function handles = initializeBicycleHandles(handles, ax, ~, cfg)
handles.bicycleFrames = plot(ax, nan, nan, '-', ...
    'Color', [0.12, 0.19, 0.22], 'LineWidth', 2.2, 'Visible', 'off');
handles.bicycleWheels = patch(ax, nan, nan, [0.72 0.75 0.70], ...
    'FaceAlpha', 0.35, 'EdgeColor', [0.12 0.17 0.17], ...
    'LineWidth', 1.5, 'Visible', 'off');
handles.bicycleRiderBodies = plot(ax, nan, nan, '-', ...
    'Color', [0.26 0.35 0.38], 'LineWidth', 3.5, 'Visible', 'off');
handles.bicycleRiders = patch(ax, nan, nan, [0.93 0.73 0.56], ...
    'EdgeColor', [0.30 0.22 0.17], 'Visible', 'off');
handles.bicycleWarning = text(ax, 0, 0, '', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'FontSize', 14, 'Color', [0.78, 0.09, 0.07], ...
    'BackgroundColor', [1.0, 0.91, 0.60], 'Margin', 6, 'Visible', 'off');
handles.bicycleImpact = plot(ax, nan, nan, '-', ...
    'Color', [0.95, 0.62, 0.08], 'LineWidth', 2.2, 'Visible', 'off');
end

function handles = initializeBusHandles(handles, ax, world, cfg)
busCount = numel(world.mechanic.bus.phaseOffsets);
handles.buses = gobjects(busCount, 1);
handles.busSprites = gobjects(busCount, 1);
handles.busWhiteBands = gobjects(0, 1);
handles.busWindows = gobjects(0, 1);
handles.busWheels = gobjects(0, 1);
handles.busLabels = gobjects(busCount, 1);
handles.busDetails = gobjects(0, 1);
handles.busHubs = gobjects(0, 1);
[busVertices, busFaces, busColours] = busPatchGeometry();
handles.busLocalVertices = busVertices;
for index = 1:busCount
    % Keep the invisible rectangle as the authoritative render hitbox for
    % diagnostics, while one textured surface replaces six moving vector
    % objects.  The sprite is generated locally, so no image quality is lost
    % through file compression or runtime resampling.
    handles.buses(index) = rectangle(ax, 'Position', [0, 0, 1, 1], ...
        'FaceColor', 'none', 'EdgeColor', 'none', 'Visible', 'off');
    handles.busSprites(index) = patch(ax, ...
        'Vertices', busVertices, 'Faces', busFaces, ...
        'FaceVertexCData', busColours, 'FaceColor', 'flat', ...
        'EdgeColor', 'none', 'Visible', 'off', 'UserData', busVertices);
    handles.busLabels(index)=text(ax,0,0,'北京理工大学', ...
        'FontName',cfg.render.fontName,'FontWeight','bold','FontSize',6, ...
        'Color',[.08 .16 .15],'HorizontalAlignment','center','Visible','off');
end
lampCount = size(world.mechanic.bus.lampColliders, 1);
handles.lampPoles = gobjects(lampCount, 1);
handles.lampArms = gobjects(lampCount, 1);
handles.lampHeads = gobjects(lampCount, 1);
for index = 1:lampCount
    rect = world.mechanic.bus.lampColliders(index, :);
    centreX = rect(1) + rect(3) / 2;
    capY = rect(2) + 0.48 * rect(4);
    handles.lampPoles(index) = plot(ax, nan, nan, '-', ...
        'Color', [0.18, 0.23, 0.25], 'LineWidth', 3.0, 'Visible', 'off');
    handles.lampArms(index) = plot(ax, nan, nan, '-', ...
        'Color', [0.18, 0.23, 0.25], 'LineWidth', 2.2, 'Visible', 'off');
    handles.lampHeads(index) = plot(ax, nan, nan, 'o', ...
        'MarkerSize', 7, 'MarkerFaceColor', [0.94, 0.82, 0.35], ...
        'MarkerEdgeColor', [0.28, 0.25, 0.16], 'Visible', 'off');
    set(handles.lampPoles(index), 'XData', [centreX, centreX], ...
        'YData', [1.0, capY + 0.28]);
    set(handles.lampArms(index), ...
        'XData', centreX + [-0.82, -0.56, -0.24, 0, 0.24, 0.56, 0.82], ...
        'YData', capY + [0.04, 0.17, 0.25, 0.29, 0.25, 0.17, 0.04]);
    set(handles.lampHeads(index), ...
        'XData', centreX + [-0.82, 0.82], ...
        'YData', capY + [0.01, 0.01]);
end
handles.finishNotice = text(ax, 0, 0, '', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'FontSize', 11, ...
    'Color', [0.04, 0.31, 0.16], 'BackgroundColor', [0.91, 0.98, 0.88], ...
    'Margin', 5, 'Visible', 'off');
finish = world.finish;
set(handles.finishNotice, 'Position', ...
    [finish(1) + finish(3) / 2, finish(2) + finish(4) + 0.45, 0]);
end

function [vertices, faces, colours] = busPatchGeometry()
% One patch with multiple coloured faces is much cheaper than seven HG
% objects per vehicle while retaining windows, stripe, wheels and hubs.
polygons = { ...
    [0.02 .08; .98 .08; .98 .82; .94 1; .06 1; .02 .88], ...
    [.02 .12; .98 .12; .98 .38; .02 .38], ...
    [.07 .56; .18 .56; .18 .86; .07 .86], ...
    [.22 .56; .34 .56; .34 .86; .22 .86], ...
    [.38 .56; .50 .56; .50 .86; .38 .86], ...
    [.54 .56; .66 .56; .66 .86; .54 .86], ...
    [.70 .56; .82 .56; .82 .86; .70 .86], ...
    [.86 .56; .93 .56; .93 .86; .86 .86]};
faceColours = [235 240 226; 33 122 74; repmat([28 58 72], 6, 1)] / 255;
% Original side elevation informed by the two checked transport photos.
% Fine panels share this one compound patch, not dozens of moving objects.
polygons{end+1}=[.025 .40;.93 .40;.86 .51;.36 .51;.27 .62;.08 .62];
faceColours(end+1,:)=[.13 .62 .36];
polygons{end+1}=[.04 .88;.94 .88;.94 .95;.06 .97];
faceColours(end+1,:)=[.10 .16 .18];
for x=[.07 .22 .38 .54 .70]
    for edge=[0 .08]
        polygons{end+1}=[x+edge .58;x+edge+.025 .58;x+edge+.035 .85;x+edge .85]; %#ok<AGROW>
        faceColours(end+1,:)=[.61 .74 .64]; %#ok<AGROW>
    end
    polygons{end+1}=[x .80;x+.09 .76;x+.11 .81;x .85]; %#ok<AGROW>
    faceColours(end+1,:)=[.27 .39 .42]; %#ok<AGROW>
end
% Luggage doors with metal seams and latches.
for x=[.35 .49 .63 .76]
    polygons{end+1}=[x .10;x+.002 .10;x+.002 .39;x .39]; %#ok<AGROW>
    faceColours(end+1,:)=[.08 .28 .22]; %#ok<AGROW>
    polygons{end+1}=[x+.055 .30;x+.075 .30;x+.075 .32;x+.055 .32]; %#ok<AGROW>
    faceColours(end+1,:)=[.14 .18 .18]; %#ok<AGROW>
end
% Front door / windscreen / mirrors, no copied number plate or faces.
polygons=[polygons,{[.89 .10;.96 .10;.96 .84;.89 .86], ...
    [.904 .38;.947 .38;.947 .82;.904 .82], ...
    [.954 .56;.984 .56;.977 .83;.954 .88], ...
    [.975 .74;1.008 .74;1.008 .80;.975 .80], ...
    [.974 .24;.99 .24;.99 .32;.974 .32], ...
    [.018 .28;.029 .28;.029 .42;.018 .42], ...
    [.28 .97;.60 .97;.58 1;.31 1]}];
faceColours=[faceColours;.07 .13 .14;.32 .43 .43;.16 .28 .32; ...
    .11 .15 .16;.99 .94 .70;.80 .10 .07;.87 .91 .90];
for x=.045:.012:.14
    polygons{end+1}=[x .14;x+.004 .14;x+.004 .34;x .34]; %#ok<AGROW>
    faceColours(end+1,:)=[.09 .26 .20]; %#ok<AGROW>
end
% Correct round tyres and silver hubs at the two axle positions.
theta=linspace(0,2*pi,28)';
for x=[.22 .81]
    for radius=[1 .62 .23]
        polygons{end+1}=[x+.039*radius*cos(theta),.075+.182*radius*sin(theta)]; %#ok<AGROW>
        if radius==1
            color=[.06 .075 .08];
        elseif radius==.62
            color=[.63 .67 .68];
        else
            color=[.19 .23 .25];
        end
        faceColours(end+1,:)=color; %#ok<AGROW>
    end
end
maxCorners = max(cellfun(@(p) size(p, 1), polygons));
faces = nan(numel(polygons), maxCorners);
vertices = zeros(0, 2);
for index = 1:numel(polygons)
    first = size(vertices, 1) + 1;
    vertices = [vertices; polygons{index}]; %#ok<AGROW>
    faces(index, 1:size(polygons{index}, 1)) = ...
        first:(first + size(polygons{index}, 1) - 1);
end
colours = faceColours;
end

function page = createNetworkPageSurface(ax, rect, imagePath, stride)
stride = max(1, round(stride));
rgb = readGameImage(imagePath, stride);
x = rect(1) + [0, rect(3); 0, rect(3)];
y = rect(2) + [0, 0; rect(4), rect(4)];
page = surface(ax, x, y, 0.02 * ones(2), ...
    'CData', flipud(rgb), 'FaceColor', 'texturemap', ...
    'EdgeColor', 'none', 'Visible', 'off');
end
