function handles = initializeContinuousHandles(ax, world, cfg)
%INITIALIZECONTINUOUSHANDLES Create reusable handles for the seamless world.

handles.alpacaBody = rectangle(ax, 'Position', [0, 0, 1, 1], ...
    'FaceColor', [0.91, 0.76, 0.56], 'EdgeColor', [0.34, 0.22, 0.15], ...
    'LineWidth', 1.6, 'Curvature', 0.32, 'Visible', 'off');
handles.alpacaHead = rectangle(ax, 'Position', [0, 0, 1, 1], ...
    'FaceColor', [0.94, 0.81, 0.62], 'EdgeColor', [0.34, 0.22, 0.15], ...
    'LineWidth', 1.4, 'Curvature', 0.45, 'Visible', 'off');
handles.alpacaNose = plot(ax, nan, nan, 'o', 'MarkerSize', 8, ...
    'MarkerFaceColor', [0.44, 0.25, 0.19], ...
    'MarkerEdgeColor', [0.25, 0.14, 0.10], 'Visible', 'off');
handles.alpacaLegs = plot(ax, nan, nan, '-', ...
    'Color', [0.34, 0.22, 0.15], 'LineWidth', 2.0, 'Visible', 'off');
handles.alpacaWarning = text(ax, 0, 0, '阿嚏！', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', [0.76, 0.22, 0.18], ...
    'Visible', 'off');

teaCount = numel(world.mechanic.tea);
handles.tea = gobjects(teaCount, 1);
handles.teaLabel = gobjects(teaCount, 1);
for index = 1:teaCount
    handles.tea(index) = rectangle(ax, 'Position', [0, 0, 1, 1], ...
        'FaceColor', [0.88, 0.32, 0.12], 'EdgeColor', [0.38, 0.16, 0.06], ...
        'LineWidth', 1.5, 'Curvature', 0.22, 'Visible', 'off');
    handles.teaLabel(index) = text(ax, 0, 0, '热带冰红茶', ...
        'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
        'FontWeight', 'bold', 'FontSize', 8.5, ...
        'Color', [0.46, 0.16, 0.05], 'Visible', 'off');
end
end
