function handles = initializeContinuousHandles(ax, world, cfg)
%INITIALIZECONTINUOUSHANDLES Create reusable handles for the seamless world.

handles.alpacaBody = rectangle(ax, 'Position', [0, 0, 1, 1], ...
    'FaceColor', [0.91, 0.76, 0.56], 'EdgeColor', [0.34, 0.22, 0.15], ...
    'LineWidth', 1.6, 'Curvature', 0.32, 'Visible', 'off');
handles.alpacaHead = rectangle(ax, 'Position', [0, 0, 1, 1], ...
    'FaceColor', [0.94, 0.81, 0.62], 'EdgeColor', [0.34, 0.22, 0.15], ...
    'LineWidth', 1.4, 'Curvature', 0.45, 'Visible', 'off');
handles.alpacaNose = plot(ax, nan, nan, 'o', 'MarkerSize', 8, ...
    'MarkerFaceColor', [0.44, 0.25, 0.19], ...
    'MarkerEdgeColor', [0.25, 0.14, 0.10], 'Visible', 'off');
handles.alpacaLegs = plot(ax, nan, nan, '-', ...
    'Color', [0.34, 0.22, 0.15], 'LineWidth', 2.0, 'Visible', 'off');
handles.alpacaWarning = text(ax, 0, 0, '阿嚏！', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', [0.76, 0.22, 0.18], ...
    'Visible', 'off');

teaCount = numel(world.mechanic.tea);
handles.tea = gobjects(teaCount, 1);
handles.teaLabel = gobjects(teaCount, 1);
for index = 1:teaCount
    handles.tea(index) = rectangle(ax, 'Position', [0, 0, 1, 1], ...
        'FaceColor', [0.88, 0.32, 0.12], 'EdgeColor', [0.38, 0.16, 0.06], ...
        'LineWidth', 1.5, 'Curvature', 0.22, 'Visible', 'off');
    handles.teaLabel(index) = text(ax, 0, 0, '热带冰红茶', ...
        'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
        'FontWeight', 'bold', 'FontSize', 8.5, ...
        'Color', [0.46, 0.16, 0.05], 'Visible', 'off');
end

handles.networkFields = gobjects(2, 1);
handles.networkFieldLabels = gobjects(2, 1);
fieldLabels = {'用户名', '密码'};
for index = 1:2
    handles.networkFields(index) = rectangle(ax, ...
        'Position', [0, 0, 1, 1], 'FaceColor', [0.90, 0.94, 0.98], ...
        'EdgeColor', [0.19, 0.29, 0.42], 'LineWidth', 1.6, ...
        'Curvature', 0.06, 'Visible', 'off');
    handles.networkFieldLabels(index) = text(ax, 0, 0, ...
        fieldLabels{index}, 'HorizontalAlignment', 'center', ...
        'FontName', cfg.render.fontName, 'FontWeight', 'bold', ...
        'Color', [0.12, 0.22, 0.34], 'Visible', 'off');
end
handles.networkCheckbox = rectangle(ax, 'Position', [0, 0, 1, 1], ...
    'FaceColor', [0.94, 0.96, 0.98], 'EdgeColor', [0.19, 0.29, 0.42], ...
    'LineWidth', 1.5, 'Visible', 'off');
handles.networkCheckboxLabel = text(ax, 0, 0, '', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'FontSize', 8.5, 'Visible', 'off');
handles.networkLogin = rectangle(ax, 'Position', [0, 0, 1, 1], ...
    'FaceColor', [0.67, 0.76, 0.82], 'EdgeColor', [0.18, 0.30, 0.38], ...
    'LineWidth', 1.7, 'Curvature', 0.10, 'Visible', 'off');
handles.networkLoginLabel = text(ax, 0, 0, '', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', 'white', 'Visible', 'off');
handles.networkGate = rectangle(ax, 'Position', [0, 0, 1, 1], ...
    'FaceColor', [0.88, 0.25, 0.21], 'EdgeColor', [0.42, 0.08, 0.07], ...
    'LineWidth', 1.8, 'FaceAlpha', 0.70, 'Visible', 'off');
handles.networkElevator = rectangle(ax, 'Position', [0, 0, 1, 1], ...
    'FaceColor', [0.20, 0.66, 0.83], 'EdgeColor', [0.05, 0.33, 0.50], ...
    'LineWidth', 1.8, 'Curvature', 0.08, 'Visible', 'off');
handles.networkElevatorLabel = text(ax, 0, 0, '自助服务', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', [0.05, 0.27, 0.40], 'Visible', 'off');
handles.rechargePads = gobjects(2, 1);
handles.rechargeLabels = gobjects(2, 1);
rechargeLabels = {'在线充值', '经费卡充值'};
for index = 1:2
    handles.rechargePads(index) = rectangle(ax, ...
        'Position', [0, 0, 1, 1], 'FaceColor', [0.31, 0.75, 0.86], ...
        'EdgeColor', [0.05, 0.37, 0.54], 'LineWidth', 1.5, ...
        'Curvature', 0.10, 'Visible', 'off');
    handles.rechargeLabels(index) = text(ax, 0, 0, ...
        rechargeLabels{index}, 'HorizontalAlignment', 'center', ...
        'FontName', cfg.render.fontName, 'FontWeight', 'bold', ...
        'FontSize', 7.5, 'Color', [0.04, 0.30, 0.43], 'Visible', 'off');
end

handles.fountainBase = rectangle(ax, 'Position', [0, 0, 1, 1], ...
    'FaceColor', [0.39, 0.76, 0.88], 'EdgeColor', [0.08, 0.42, 0.60], ...
    'LineWidth', 1.6, 'Curvature', 0.18, 'Visible', 'off');
handles.fountainJet = plot(ax, nan, nan, '-', ...
    'Color', [0.67, 0.92, 1.0], 'LineWidth', 8.0, 'Visible', 'off');
handles.fountainLabel = text(ax, 0, 0, '喷泉上桥', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', [0.05, 0.35, 0.54], 'Visible', 'off');
handles.signalHousing = rectangle(ax, 'Position', [105.15, 4.30, 1.35, 3.55], ...
    'FaceColor', [0.16, 0.20, 0.22], 'EdgeColor', [0.04, 0.06, 0.07], ...
    'LineWidth', 1.5, 'Curvature', 0.15, 'Visible', 'off');
handles.signalLights = gobjects(3, 1);
for index = 1:3
    handles.signalLights(index) = plot(ax, nan, nan, 'o', ...
        'MarkerSize', 11, 'MarkerFaceColor', [0.27, 0.29, 0.30], ...
        'MarkerEdgeColor', [0.06, 0.07, 0.08], 'LineWidth', 1.0, ...
        'Visible', 'off');
end
handles.signalLabel = text(ax, 105.8, 8.15, '', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', [0.12, 0.18, 0.22], 'Visible', 'off');
handles.routeLabel = text(ax, 94.0, 8.4, '', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.render.fontName, ...
    'FontWeight', 'bold', 'Color', [0.12, 0.18, 0.22], 'Visible', 'off');
handles.cars = gobjects(size(world.mechanic.traffic.carData, 1), 1);
for index = 1:numel(handles.cars)
    handles.cars(index) = rectangle(ax, 'Position', [0, 0, 1, 1], ...
        'FaceColor', [0.88, 0.29, 0.20], 'EdgeColor', [0.35, 0.08, 0.06], ...
        'LineWidth', 1.6, 'Curvature', 0.22, 'Visible', 'off');
end
handles.crowd = gobjects(size(world.mechanic.traffic.crowdData, 1), 1);
for index = 1:numel(handles.crowd)
    handles.crowd(index) = rectangle(ax, 'Position', [0, 0, 1, 1], ...
        'FaceColor', [0.56, 0.48, 0.76], 'EdgeColor', [0.22, 0.16, 0.39], ...
        'LineWidth', 1.1, 'Curvature', 0.48, 'Visible', 'off');
end
end
